### ISSUE TITLE
Uppercase

### ISSUE THREAD

**Issue by stivaugoin** [derzunov/redux-react-native-i18n#3]
I have a component to show some text with a specific style. This component need to uppercase the text. Is it possible to uppercase the result of `<Loc>` without set my text uppercase in the dictionary?

This is my current component
```
const H2 = props => (
  <Loc
    locKey={props.labelKey}
    style={[styles.label, props.style]}
  />
);

```

Thanks

**Comment by derzunov** [comment]
Hi, Steve!

I'll think about implementing feature like that. 
Stay in touch :)
Thank you!

**Comment by derzunov** [comment]
Hi Steve!
Text transformation is not a functionality of i18n. Sorry :(
You can use special keys for uppercase values in your dictionary.

**Comment by stivaugoin** [comment]
Alright, no problem. Thank you
