### ISSUE TITLE
What's the difference between redux-react-native-i18n and redux-react-i18n?

### ISSUE THREAD

**Issue by zedtux** [derzunov/redux-react-native-i18n#7]
I don't really see the difference between the 2 packages.

Can you explain it?

**Comment by derzunov** [comment]
I don't think it's the ISSUE :) So I'm closing it.
If you want to talk, write me on derzunov.work@gmail.com

**Comment by zedtux** [comment]
Why don't you answer here? The point is that people can have the information immediately.

Of course it isn't an ISSUE, nobody said there is an issue ... Well ... actually ... YES it is an issue! Your documentation is completely unclear on this point, and it needs to be updated, so please reopen the issue so that the `README.md` file could be updated and giving the information to everybody !

Thank you.

**Comment by derzunov** [comment]
:)
The difference is in presentational and container components. 
This package uses `<Text>` from react-native in view-component instead of `<span>`.
Okay, I'll update the README.md file.

**Comment by derzunov** [comment]
README.md updated.
